build: off
cache:
  - '%USERPROFILE%\.platformio\packages -> appveyor.yml'

environment:
  BUCKET_NAME: svitlopulse.prod.releases
  AWS_REGION: eu-west-1
  AWS_ACCESS_KEY_ID:
    secure: bxCJoncg+CElwAozSwvx8hkmflN/oUnK4ldwGI38w88=
  AWS_SECRET_ACCESS_KEY:
    secure: Q8ANDgAueDwZJn126EDTaCk/lPKNgPLe6BUf6ICcNio/TOOVsauPtm3/Yw55Kps7

init:
  - git config --global core.autocrlf input

install:
    - cmd: SET PATH=%PATH%;C:\Python312-x64\Scripts
    - cmd: pip3 install -U platformio
    - cmd: pip3 install -r requirements.txt

test_script:
    - cmd: pio run
    - cmd: python gen_manifest.py
    - cmd: python deploy.py

artifacts:
  - path: .pio/build/*/*-merged.bin
  - path: manifest.json


deploy:
  - provider: GitHub
    description: Draft release
    auth_token:
      secure: iJAvKTreoG/55DiyN7ViE+Q3Vu9BvurMk2VXzlN2bOX2i+G31ijdS5eD1u/iKJZ2
    draft: true
    on:
      branch: master
      #APPVEYOR_REPO_TAG: true