build: off
cache:
  - '%USERPROFILE%\.platformio\packages -> appveyor.yml'
init:
  - git config --global core.autocrlf input

install:
    - cmd: SET PATH=%PATH%;C:\Python312-x64\Scripts
    - cmd: pip3 install -U platformio

test_script:
    - cmd: pio run
    - cmd: python gen_manifest.py

after_test:
  - ps: Get-ChildItem .pio\build\*\*-merged.bin | % { Push-AppveyorArtifact $_.FullName -FileName $Env:APPVEYOR_BUILD_VERSION/$_.Name }
  - ps: Get-ChildItem .pio\build\*\*-manifest.json | % { Push-AppveyorArtifact $_.FullName -FileName $Env:APPVEYOR_BUILD_VERSION/$_.Name }
  - ps: echo $Env:APPVEYOR_BUILD_VERSION > latest.txt
  - ps: Push-AppveyorArtifact manifest.json -FileName $Env:APPVEYOR_BUILD_VERSION/manifest.json
  - ps: Push-AppveyorArtifact latest.txt

deploy:
  - provider: GitHub
    description: Draft release
    auth_token:
      secure: iJAvKTreoG/55DiyN7ViE+Q3Vu9BvurMk2VXzlN2bOX2i+G31ijdS5eD1u/iKJZ2
    draft: true
    on:
      branch: master
      #APPVEYOR_REPO_TAG: true
  - provider: S3
    bucket: svitlopulse.prod.releases
    region: eu-west-1
    folder: $(APPVEYOR_BUILD_VERSION)
    set_public: true
    access_key_id:
      secure: M06ZEA76yIIthDYokZg4PLdWfosyP/xANtRGuF2FiJE=
    secret_access_key:
      secure: MZbubX2fm5rR08gL8y3iKEzLA2/W0JO2HZpNpxByjwpJpr5lTSlLFm2/XqO8ePmE
    on:
      branch: master
      #APPVEYOR_REPO_TAG: true