build: off
cache:
  - '%USERPROFILE%\.platformio -> appveyor.yml'
init:
  - git config --global core.autocrlf input

install:
    - cmd: SET PATH=%PATH%;C:\Python312-x64\Scripts
    - cmd: pip3 install -U platformio

test_script:
    - cmd: pio run -e esp-c3-13u-4m


artifacts:
  - path: .pio/build/*/*-merged.bin
  - path: .pio/build/*/*-manifest.json

deploy:
  - provider: GitHub
    description: Draft release
    auth_token:
      secure: iJAvKTreoG/55DiyN7ViE+Q3Vu9BvurMk2VXzlN2bOX2i+G31ijdS5eD1u/iKJZ2
    draft: true
    on:
      branch: master
      #APPVEYOR_REPO_TAG: true
  - provider: S3
    bucket: svitlopulse.prod.releases
    region: eu-west-1
    folder: $(APPVEYOR_BUILD_VERSION)
    set_public: true
    access_key_id:
      secure: M06ZEA76yIIthDYokZg4PLdWfosyP/xANtRGuF2FiJE=
    secret_access_key:
      secure: MZbubX2fm5rR08gL8y3iKEzLA2/W0JO2HZpNpxByjwpJpr5lTSlLFm2/XqO8ePmE
    on:
      branch: master
      #APPVEYOR_REPO_TAG: true